### ISSUE TITLE
update website for seaborn styles

### ISSUE THREAD

**Issue by flying-sheep** [tonysyu/matplotlib-style-gallery#2]
…which are now included in matplotlib

**Comment by tonysyu** [comment]
Hmm... this should just update on its own based on your install version of matplotlib. Have you verified that the version you're running has those styles, and that it's the same version of matplotlib you're running with this project?

**Comment by flying-sheep** [comment]
no, i mean on http://tonysyu.github.io/raw_content/matplotlib-style-gallery/gallery.html

**Comment by tonysyu** [comment]
Good point. I've updated that page and actually added better navigation between plots. Also, I wrote a [quick post](https://tonysyu.github.io/matplotlib-style-gallery.html#.VvoAzxIrKV4) about it.

Thanks for reporting issues!

**Comment by flying-sheep** [comment]
gladly!
